remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Documentation of DuckPy Jeedom plugins
description: Documentations Jeedom

author:
  name: DuchkPy

languages: ["en", "fr"]
defaultLang: fr
languageNames:
  fr: Français
  en: English

plugins:
  - jemoji
  - jekyll-seo-tag

show_downloads: false

# Markdown Settings
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]